import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://thinking-tester-contact-list.herokuapp.com/');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('pruebas@prue.com.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('1234567');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Add a New Contact' }).click();
  await page.getByRole('textbox', { name: '* First Name:' }).click();
  await page.getByRole('textbox', { name: '* First Name:' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* First Name:' }).fill('F');
  await page.getByRole('textbox', { name: '* First Name:' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* First Name:' }).fill('Framework');
  await page.getByRole('textbox', { name: '* Last Name:' }).click();
  await page.getByRole('textbox', { name: '* Last Name:' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* Last Name:' }).fill('P');
  await page.getByRole('textbox', { name: '* Last Name:' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* Last Name:' }).fill('Playwright');
  await page.getByRole('textbox', { name: 'Date of Birth:' }).click();
  await page.getByRole('textbox', { name: 'Date of Birth:' }).fill('1984-04-01');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('playwright@gmail.com.co');
  await page.getByRole('textbox', { name: 'Phone:' }).click();
  await page.getByRole('textbox', { name: 'Phone:' }).fill('5555555555');
  await page.getByRole('textbox', { name: 'Street Address 1:' }).click();
  await page.getByRole('textbox', { name: 'Street Address 1:' }).fill('calle 154a 99 32');
  await page.getByRole('textbox', { name: 'City:' }).click();
  await page.getByRole('textbox', { name: 'City:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'City:' }).fill('B');
  await page.getByRole('textbox', { name: 'City:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'City:' }).fill('Bogota');
  await page.getByRole('textbox', { name: 'State or Province:' }).click();
  await page.getByRole('textbox', { name: 'State or Province:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'State or Province:' }).fill('C');
  await page.getByRole('textbox', { name: 'State or Province:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'State or Province:' }).fill('Colombia');
  await page.getByRole('textbox', { name: 'Postal Code:' }).click();
  await page.getByRole('textbox', { name: 'Postal Code:' }).fill('111121');
  await page.getByRole('textbox', { name: 'Country:' }).click();
  await page.getByRole('textbox', { name: 'Country:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Country:' }).fill('B');
  await page.getByRole('textbox', { name: 'Country:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Country:' }).fill('Bogota');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('cell', { name: 'Framework Playwright' }).click();
  await page.getByText('Framework').click();
});