import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://thinking-tester-contact-list.herokuapp.com/');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('tester@tester.com.co');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('1234567');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Add a New Contact' }).click();
  await page.getByRole('textbox', { name: '* First Name:' }).click();
  await page.getByRole('textbox', { name: '* First Name:' }).fill('tester1');
  await page.getByRole('textbox', { name: '* Last Name:' }).click();
  await page.getByRole('textbox', { name: '* Last Name:' }).fill('tester2');
  await page.getByRole('textbox', { name: 'Date of Birth:' }).click();
  await page.getByRole('textbox', { name: 'Date of Birth:' }).fill('1984-06-01');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('tester@tester.com.co');
  await page.getByRole('textbox', { name: 'Phone:' }).click();
  await page.getByRole('textbox', { name: 'Phone:' }).fill('1111111111');
  await page.getByRole('textbox', { name: 'Street Address 1:' }).click();
  await page.getByRole('textbox', { name: 'Street Address 1:' }).fill('calle 1 1 11');
  await page.getByRole('textbox', { name: 'City:' }).click();
  await page.getByRole('textbox', { name: 'City:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'City:' }).fill('B');
  await page.getByRole('textbox', { name: 'City:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'City:' }).fill('Bogota');
  await page.getByRole('textbox', { name: 'State or Province:' }).click();
  await page.getByRole('textbox', { name: 'State or Province:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'State or Province:' }).fill('B');
  await page.getByRole('textbox', { name: 'State or Province:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'State or Province:' }).fill('Bogota');
  await page.getByRole('textbox', { name: 'Postal Code:' }).click();
  await page.getByRole('textbox', { name: 'Postal Code:' }).click();
  await page.getByRole('textbox', { name: 'Postal Code:' }).fill('110010');
  await page.getByRole('textbox', { name: 'Country:' }).click();
  await page.getByRole('textbox', { name: 'Country:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Country:' }).fill('Colombia');
  await page.getByRole('textbox', { name: 'Country:' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('cell', { name: 'tester1 tester2' }).click();
});