
Feature: Heroku_CrearUsuario

Scenario: Flujo Heroku_CrearUsuario
  Given el usuario está en la aplicación
  And hace clic en "elemento"
  And hace clic en "Email"
  When el usuario ingresa "tester@tester.com.co" en "Email"
  And hace clic en "Password"
  And ingresa "1234567" en "Password"
  And hace clic en "Submit"
  And hace clic en "Add a New Contact"
  And hace clic en "* First Name:"
  And completa "* First Name:" con "tester1"
  And hace clic en "* Last Name:"
  And completa "* Last Name:" con "tester2"
  And hace clic en "Date of Birth:"
  And completa "Date of Birth:" con "1984-06-01"
  And hace clic en "Email:"
  When el usuario ingresa "tester@tester.com.co" en "Email:"
  And hace clic en "Phone:"
  And completa "Phone:" con "1111111111"
  And hace clic en "Street Address 1:"
  And completa "Street Address 1:" con "calle 1 1 11"
  And hace clic en "City:"
  And completa "City:" con "B"
  And completa "City:" con "Bogota"
  And hace clic en "State or Province:"
  And completa "State or Province:" con "B"
  And completa "State or Province:" con "Bogota"
  And hace clic en "Postal Code:"
  And completa "Postal Code:" con "110010"
  And hace clic en "Country:"
  And completa "Country:" con "Colombia"
  And hace clic en "Country:"
  And hace clic en "Submit"
  And hace clic en "tester1 tester2"
  Then la página está disponible sin errores
